server:
  port: 8085
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.135.123
    username: hsource
    password: hsource
    virtual-host: /hsource
  redis:
    host: 192.168.135.123

hs:
  sms:
    accessKeyId: JWffwFJIwada # 你自己的accessKeyId
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称