server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.135.123:3307/hs?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    username: root
    password: zxw123
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
