server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.135.123:3307/hs?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    username: root
    password: zxw123
  rabbitmq:
    host: 192.168.135.123
    username: hsource
    password: hsource
    virtual-host: /hsource
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        multiplier: 2
        max-interval: 30000ms
      exchange: hs.item.exchange
    publisher-confirms: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
      add-mappings: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
